FRONTEND/ENDUSER/ZZCORE.WEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ZZCORE.WEB.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GuestHome()
        {
            return View();
        }
        public ActionResult UserHome()
        {
            return View();
        }
        public ActionResult UserPrivate()
        {
            return View();
        }
        public ActionResult UserShops()
        {
            return View();
        }
        public ActionResult UserFriends()
        {
            return View();
        }
        public ActionResult UserGuestView()
        {
            return View();
        }
        public ActionResult UserBuying()
        {
            return View();
        }
        public ActionResult UserEarning()
        {
            return View();
        }
        public ActionResult PagePrivate()
        {
            return View();
        }
        public ActionResult SearchResultPeople()
        {
            return View();
        }
        public ActionResult SearchResultPosts()
        {
            return View();
        }
        public ActionResult SearchResultShops()
        {
            return View();
        }
        public ActionResult SearchResultProducts()
        {
            return View();
        }
        public ActionResult PageGuestView()
        {
            return View();
        }
        public ActionResult ProductDetails()
        {
            return View();
        }
        public ActionResult Checkout()
        {
            return View();
        }
        public ActionResult Success()
        {
            return View();
        }
        public ActionResult GuestCategories()
        {
            return View();
        }
        public ActionResult Chat()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Blank()
        {
            return View();
        }
    }
}

FRONTEND/ENDUSER/ZZCORE.WEB/Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace ZZCORE.WEB.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl)
        {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);
            return Redirect(returnUrl);
        }
    }
}

FRONTEND/ENDUSER/ZZCORE.WEB/Views/Home/Blank.cshtml
<div class="head-fixed-placeholder">
    <div class="head-fixed">
        @Html.Partial("_Head_user")
    </div>
</div>
<div class="container">
    <div class="user-home-wrapper">
        <div class="user-home-left" id="user-home-left">
            <div id="user-home-left-fixed" class="user-home-left-fixed">
                @Html.Partial("_UserMenuVerticle")
            </div>
        </div>
        <div class="user-home-center">
            Nội dung chưa có
        </div>
        <div class="user-home-right">
            <div id="user-home-right-fixed" class="user-home-right-fixed">
                @Html.Partial("_FriendListVerticle")
            </div>
        </div>
    </div>
</div>

FRONTEND/ENDUSER/ZZCORE.WEB/Views/Home/Chat.cshtml
<div class="head-fixed-placeholder">
    <div class="head-fixed">
        @Html.Partial("_Head_user")
    </div>
</div>
<div class="container">
    <div class="cover-image-wrapper">
        <img src="~/Content/img/stocks/pexels-photo-547115.jpeg" />
        <span class="username">Camella Yaniki</span>
        <button class="change-cover-button"><i class="material-icons">camera_enhance</i>Thay đổi ảnh bìa</button>
    </div>
    @Html.Partial("_Breadcrumbs_user")
    <div class="messenger-wrapper">
        <div class="messenger-left">
            <div class="messenger-left-head">
                <div class="settings">
                    <span>Hộp thư</span>
                    <div class="dropdown dropdown-btn float-right">
                        <div class="label"><i class="material-icons">settings</i></div>
                        <div class="content content-180">
                            <ul class="dropdown-btns">
                                <li><a href="#">Cài đặt</a></li>
                                <li class="separator"></li>
                                <li><a href="#">Hướng dẫn</a></li>
                                <li><a href="#">Báo cáo sự cố</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <form>
                    <div class="control textbox bg-white">
                        <input type="text" value="" name="messengerSearch" id="messengerSearch" />
                        <label for="messengerSearch">Tìm kiếm trong hộp thư</label>
                        <button type="submit"><i class="material-icons">search</i></button>
                    </div>
                </form>
            </div>
            <div class="messenger-left-body">
                <a href="" class="message">
                    <img src="~/Content/img/icons/avatar2.jpg" />
                    <!--
        -->
                    <div class="message-content"><span>Niaomei Yaky</span><small class="read"><i class="material-icons">check</i> Finished her are its honoured drawings nor. Pretty see mutual thrown all not edward ten</small></div>
                    <div class="status"><time>4 phút trước</time></div>
                </a>
                <a href="" class="message">
                    <img src="~/Content/img/icons/avatar3.jpg" />
                    <!--
        -->
                    <div class="message-content"><span>Niaomei Yaky</span><small class="">Finished her are its honoured drawings nor. Pretty see mutual thrown all not edward ten</small></div>
                    <div class="status"><time>4 phút trước</time></div>
                </a>
                <a href="" class="message">
                    <img src="~/Content/img/icons/avatar4.jpg" />
                    <!--
        -->
                    <div class="message-content"><span>Niaomei Yaky</span><small class="read"><i class="material-icons">check</i> Finished her are its honoured drawings nor. Pretty see mutual thrown all not edward ten</small></div>
                    <div class="status"><time>4 phút trước</time></div>
                </a>
            </div>
        </div>
        <div class="messenger-right">
            b
        </div>
    </div>
</div>

FRONTEND/ENDUSER/ZZCORE.WEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<script src="~/Scripts/controllers/home.ctrl.js"></script>
@Html.Partial("_Head_guest")
@Html.Partial("_Breadcrumbs_guest")
<div class="container" ng-controller="HomeCtrl as ctrl">
    <div class="row">
        <div class="col-xs-7">
            <table class="intro-box" style="display: block; width: 100%;">
                <tr>
                    <td width=""><span class="material-icons">group</span></td>
                    <td>Kết nối, nhắn tin với bạn bè</td>
                </tr>
                <tr>
                    <td width=""><span class="material-icons">textsms</span></td>
                    <td>Cùng bàn luận nội dung mọi người chia sẻ</td>
                </tr>
                <tr>
                    <td width=""><span class="material-icons">pages</span></td>
                    <td>Theo dõi những sở thích của bạn</td>
                </tr>
                <tr>
                    <td width=""><span class="material-icons">shopping_basket</span></td>
                    <td>Mua sắm được tích luỹ tiền</td>
                </tr>
                <tr>
                    <td width=""><span class="material-icons">monetization_on</span></td>
                    <td>Kinh doanh, kiếm tiền</td>
                </tr>
            </table>
        </div>
        <div class="col-xs-5">
            <form method="post" class="margin-top-30">
                <h1>Tạo tài khoản mới</h1>
                <h5>Miễn phí và sẽ luôn như vậy</h5>
                <div class="margin-bottom-30"></div>
                <div class="row">
                    <div class="col-xs-7">
                        <div class="control bordered textbox">
                            <input type="text" id="ho" name="ho" value="" />
                            <label for="ho">Họ và Tên đệm</label>
                        </div>
                    </div>
                    <div class="col-xs-5">
                        <div class="control bordered textbox">
                            <input type="text" id="ten" name="ten" value="" />
                            <label for="ten">Tên</label>
                        </div>
                    </div>
                </div>
                <div class="control bordered textbox margin-top-20">
                    <input type="text" id="email" name="email" value="" />
                    <label for="email">Số điện thoại hoặc email</label>
                </div>
                <div class="control bordered textbox margin-top-20">
                    <input type="text" id="matKhau-signup" name="matKhau" value="" />
                    <label for="matKhau">Nhập mật khẩu</label>
                </div>
                <h6 class="margin-top-20">Ngày sinh</h6>
                <div class="row">
                    <div class="col-xs-4">
                        <select class="sumoselect" name="ngaySinh">
                            @for (var i = 1; i <= 31; i++)
                            {
                                <option value="@i">@i</option>
                            }
                        </select>
                    </div>
                    <div class="col-xs-4">
                        <select class="sumoselect" name="ngaySinh">
                            @for (var i = 1; i <= 12; i++)
                            {
                                <option value="@i">@i</option>
                            }
                        </select>
                    </div>
                    <div class="col-xs-4">
                        <select class="sumoselect" name="ngaySinh">
                            @for (var i = 1905; i <= System.DateTime.Now.Year; i++)
                            {
                                <option value="@i">@i</option>
                            }
                        </select>
                    </div>
                </div>
                <p>
                    Bằng cách nhấp vào Tạo tài khoản, bạn đồng ý với <a href="#">Điều khoản</a> của chúng tôi và rằng bạn đã đọc <a href="#">Chính sách dữ liệu</a> của chúng tôi.
                </p>
                <button type="submit" class="btn-secondary margin-top-15" ng-click="loadInit()">TẠO TÀI KHOẢN</button>
            </form>
        </div>
    </div>
    <div class="margin-top-50">&nbsp;</div>
    <div class="margin-top-50">&nbsp;</div>

</div>
@Html.Partial("_Footer")

FRONTEND/ENDUSER/ZZCORE.WEB/Views/Home/SearchResultPeople.cshtml
<div class="head-fixed-placeholder">
    <div class="head-fixed">
        @Html.Partial("_Head_user")
    </div>
</div>
<div class="container">
    <div class="user-home-wrapper">
        <div class="user-home-left" id="user-home-left">
            <div id="user-home-left-fixed" class="user-home-left-fixed">
                @Html.Partial("_UserMenuVerticle")
            </div>
        </div>
        <div class="user-home-center">
            <div class="breadcrumbs-container padding-left-10">
                <ul class="breadcrumbs">
                    <li class="active"><a href="/Home/SearchResultPeople">Người dùng</a></li>
                    <li class="separator"></li>
                    <li class=""><a href="/Home/SearchResultPosts">Nhật ký</a></li>
                    <li class="separator"></li>
                    <li class=""><a href="/Home/SearchResultShops">Gian hàng</a></li>
                    <li class="separator"></li>
                    <li class=""><a href="/Home/SearchResultProducts">Sản phẩm</a></li>
                </ul>
            </div>
            <h2 class="txt-secondary padding-left-10">Kết quả tìm kiếm từ khóa "Alena"</h2>
            <div class="friends-wrapper full-width">
                <div class="friend-block">
                    <img src="~/Content/img/icons/avatar2.jpg" />
                    <div>
                        <a href="">Alena Roth <small>(13 bạn chung)</small></a>
                        <span>TP. Hồ Chí Minh</span>
                        <div class="friend-buttons">
                            <div class="dropdown dropdown-btn">
                                <span class="label"><i class="material-icons">check</i> Bạn bè</span>
                                <div class="content content-180">
                                    <ul class="dropdown-btns">
                                        <li><a href="#">Nhận thông báo</a></li>
                                        <li class="separator"></li>
                                        <li><a href="#">Bạn thân</a></li>
                                        <li><a href="#">Người quen</a></li>
                                        <li><a href="#">Đồng nghiệp</a></li>
                                        <li><a href="#">Thêm vào nhóm...</a></li>
                                        <li class="separator"></li>
                                        <li><a href="#">Giới thiệu bạn với...</a></li>
                                        <li class="separator"></li>
                                        <li><a href="#">Hủy kết bạn</a></li>
                                    </ul>
                                </div>
                            </div>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
                <div class="friend-block">
                    <img src="~/Content/img/icons/avatar2.jpg" />
                    <div>
                        <a href="">Alena Roth <small>(13 bạn chung)</small></a>
                        <span>TP. Hồ Chí Minh</span>
                        <div class="friend-buttons">
                            <div class="dropdown dropdown-btn">
                                <span class="label"><i class="material-icons">check</i> Bạn bè</span>
                                <div class="content content-180">
                                    <ul class="dropdown-btns">
                                        <li><a href="#">Nhận thông báo</a></li>
                                        <li class="separator"></li>
                                        <li><a href="#">Bạn thân</a></li>
                                        <li><a href="#">Người quen</a></li>
                                        <li><a href="#">Đồng nghiệp</a></li>
                                        <li><a href="#">Thêm vào nhóm...</a></li>
                                        <li class="separator"></li>
                                        <li><a href="#">Giới thiệu bạn với...</a></li>
                                        <li class="separator"></li>
                                        <li><a href="#">Hủy kết bạn</a></li>
                                    </ul>
                                </div>
                            </div>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
                <div class="friend-block">
                    <img src="~/Content/img/icons/avatar2.jpg" />
                    <div>
                        <a href="">Alena Roth <small>(13 bạn chung)</small></a>
                        <span>TP. Hồ Chí Minh</span>
                        <div class="friend-buttons">
                            <div class="dropdown dropdown-btn">
                                <span class="label"><i class="material-icons">check</i> Bạn bè</span>
                                <div class="content content-180">
                                    <ul class="dropdown-btns">
                                        <li><a href="#">Nhận thông báo</a></li>
                                        <li class="separator"></li>
                                        <li><a href="#">Bạn thân</a></li>
                                        <li><a href="#">Người quen</a></li>
                                        <li><a href="#">Đồng nghiệp</a></li>
                                        <li><a href="#">Thêm vào nhóm...</a></li>
                                        <li class="separator"></li>
                                        <li><a href="#">Giới thiệu bạn với...</a></li>
                                        <li class="separator"></li>
                                        <li><a href="#">Hủy kết bạn</a></li>
                                    </ul>
                                </div>
                            </div>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
                <div class="friend-block">
                    <img src="~/Content/img/icons/avatar2.jpg" />
                    <div>
                        <a href="">Alena Roth <small>(13 bạn chung)</small></a>
                        <span>TP. Hồ Chí Minh</span>
                        <div class="friend-buttons">
                            <button class="btn btn-small"><i class="material-icons">person_add</i>Kết bạn</button>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
                <div class="friend-block">
                    <img src="~/Content/img/icons/avatar2.jpg" />
                    <div>
                        <a href="">Alena Roth <small>(13 bạn chung)</small></a>
                        <span>TP. Hồ Chí Minh</span>
                        <div class="friend-buttons">
                            <button class="btn btn-small"><i class="material-icons">person_add</i>Kết bạn</button>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
                <div class="friend-block">
                    <img src="~/Content/img/icons/avatar2.jpg" />
                    <div>
                        <a href="">Alena Roth <small>(13 bạn chung)</small></a>
                        <span>TP. Hồ Chí Minh</span>
                        <div class="friend-buttons">
                            <button class="btn btn-small"><i class="material-icons">person_add</i>Kết bạn</button>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
                <div class="friend-block">
                    <img src="~/Content/img/icons/avatar2.jpg" />
                    <div>
                        <a href="">Alena Roth <small>(13 bạn chung)</small></a>
                        <span>TP. Hồ Chí Minh</span>
                        <div class="friend-buttons">
                            <button class="btn btn-small"><i class="material-icons">person_add</i>Kết bạn</button>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
                <div class="friend-block">
                    <img src="~/Content/img/icons/avatar2.jpg" />
                    <div>
                        <a href="">Alena Roth <small>(13 bạn chung)</small></a>
                        <span>TP. Hồ Chí Minh</span>
                        <div class="friend-buttons">
                            <button class="btn btn-small"><i class="material-icons">person_add</i>Kết bạn</button>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="user-home-right">
            <div id="user-home-right-fixed" class="user-home-right-fixed">
                @Html.Partial("_FriendListVerticle")
            </div>
        </div>
    </div>
</div>

FRONTEND/ENDUSER/ZZCORE.WEB/Views/Home/SearchResultShops.cshtml
<div class="head-fixed-placeholder">
    <div class="head-fixed">
        @Html.Partial("_Head_user")
    </div>
</div>
<div class="container">
    <div class="user-home-wrapper">
        <div class="user-home-left" id="user-home-left">
            <div id="user-home-left-fixed" class="user-home-left-fixed">
                @Html.Partial("_UserMenuVerticle")
            </div>
        </div>
        <div class="user-home-center">
            <div class="breadcrumbs-container padding-left-10">
                <ul class="breadcrumbs">
                    <li class=""><a href="/Home/SearchResultPeople">Người dùng</a></li>
                    <li class="separator"></li>
                    <li class=""><a href="/Home/SearchResultPosts">Nhật ký</a></li>
                    <li class="separator"></li>
                    <li class="active"><a href="/Home/SearchResultShops">Gian hàng</a></li>
                    <li class="separator"></li>
                    <li class=""><a href="/Home/SearchResultProducts">Sản phẩm</a></li>
                </ul>
            </div>
            <h2 class="txt-secondary padding-left-10">Kết quả tìm kiếm từ khóa "Khoai tây"</h2>
            <div class="friends-wrapper full-width">
                <div class="friend-block">
                    <img src="~/Content/img/stocks/potatoes-french-mourning-funny-162971.jpeg" />
                    <div>
                        <a href="">Khoai Tây Shop <small>98 Lượt theo dõi</small></a>
                        <span>Bạn đã mua 98 sản phẩm từ shop này</span>
                        <div class="friend-buttons">
                            <div class="dropdown dropdown-btn">
                                <span class="label"><i class="material-icons">check</i> Theo dõi</span>
                                <div class="content content-180">
                                    <ul class="dropdown-btns">
                                        <li><a href="#">Nhận thông báo</a></li>
                                        <li class="separator"></li>
                                        <li><a href="#">Bỏ theo dõi</a></li>
                                    </ul>
                                </div>
                            </div>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
                <div class="friend-block">
                    <img src="~/Content/img/stocks/potatoes-french-mourning-funny-162971.jpeg" />
                    <div>
                        <a href="">Khoai Tây Shop <small>98 Lượt theo dõi</small></a>
                        <span>Bạn đã mua 35 sản phẩm từ shop này</span>
                        <div class="friend-buttons">
                            <button class="btn btn-small"><i class="material-icons">bookmark</i>Theo dõi</button>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
                <div class="friend-block">
                    <img src="~/Content/img/stocks/potatoes-french-mourning-funny-162971.jpeg" />
                    <div>
                        <a href="">Khoai Tây Shop <small>98 Lượt theo dõi</small></a>
                        <span>Bạn đã mua 15 sản phẩm từ shop này</span>
                        <div class="friend-buttons">
                            <button class="btn btn-small"><i class="material-icons">bookmark</i>Theo dõi</button>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
                <div class="friend-block">
                    <img src="~/Content/img/stocks/potatoes-french-mourning-funny-162971.jpeg" />
                    <div>
                        <a href="">Khoai Tây Shop <small>98 Lượt theo dõi</small></a>
                        <span>Bạn đã mua 2 sản phẩm từ shop này</span>
                        <div class="friend-buttons">
                            <button class="btn btn-small"><i class="material-icons">bookmark</i>Theo dõi</button>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
                <div class="friend-block">
                    <img src="~/Content/img/stocks/potatoes-french-mourning-funny-162971.jpeg" />
                    <div>
                        <a href="">Khoai Tây Shop <small>98 Lượt theo dõi</small></a>
                        <div class="friend-buttons">
                            <button class="btn btn-small"><i class="material-icons">bookmark</i>Theo dõi</button>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
                <div class="friend-block">
                    <img src="~/Content/img/stocks/potatoes-french-mourning-funny-162971.jpeg" />
                    <div>
                        <a href="">Khoai Tây Shop <small>98 Lượt theo dõi</small></a>
                        <div class="friend-buttons">
                            <button class="btn btn-small"><i class="material-icons">bookmark</i>Theo dõi</button>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
                <div class="friend-block">
                    <img src="~/Content/img/stocks/potatoes-french-mourning-funny-162971.jpeg" />
                    <div>
                        <a href="">Khoai Tây Shop <small>98 Lượt theo dõi</small></a>
                        <div class="friend-buttons">
                            <button class="btn btn-small"><i class="material-icons">bookmark</i>Theo dõi</button>
                            <button class="btn btn-small"><i class="material-icons">sms</i>Nhắn tin</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="user-home-right">
            <div id="user-home-right-fixed" class="user-home-right-fixed">
                @Html.Partial("_FriendListVerticle")
            </div>
        </div>
    </div>
</div>

FRONTEND/ENDUSER/ZZCORE.WEB/Views/Home/Success.cshtml
<div class="head-fixed-placeholder">
    <div class="head-fixed">
        @Html.Partial("_Head_user")
    </div>
</div>
<div class="container">
    <div class="checkout-container">
        <ul class="checkout-breadcrumbs">
            <li >Thông tin đặt hàng</li>
            <li class="active">Đặt hàng</li>
        </ul>
    </div>
    <div class="checkout-success">
        <img width="92" src="~/Content/img/icons/check.svg" />
        <h5 class="txt-secondary margin-top-20 margin-bottom-30">Đặt hàng thành công</h5>
        <p>
            Chúc mừng bạn, hệ thống đã tự động tạo tài khoản cho bạn.
            Bấm <a href="#">vào đây</a> để bắt đầu khám phá
        </p>
    </div>
</div>

FRONTEND/ENDUSER/ZZCORE.WEB/Views/Shared/_Breadcrumbs_guest.cshtml
<div class="breadcrumbs-container">
    <div class="container">
        <ul class="breadcrumbs big">
            <li class='@(Request.RawUrl=="/"?"active":"")'><a href="/">TRANG CHỦ</a></li>
            <li class="separator"></li>
            <li class="@((Request.RawUrl=="/Home/GuestHome"||Request.RawUrl=="/Home/GuestCategories")?"active":"")"><a href="/Home/GuestHome">MUA SẮM</a></li>
        </ul>
    </div>
</div>

FRONTEND/ENDUSER/ZZCORE.WEB/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/packages/material-icon/material-icons.css" rel="stylesheet" />
</head>
<body>
    @Html.Partial("_ViewSwitcher")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p><i class="material-icons">account_balance</i>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
</body>
</html>

FRONTEND/ENDUSER/ZZCORE.WEB/Views/Shared/_ViewSwitcher.cshtml
<div class="view-switcher">
    @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
    {
        @Html.ActionLink("Xem trang ở chế độ Desktop", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
    } 
    else 
    {
        @: Displaying desktop view
        @Html.ActionLink("Xem trang ở chế độ di động", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
    }
</div>
<div class="margin-top-20 margin-bottom-20">
    <a href="/">[1] Guest Login</a>
    | <a href="/Home/GuestHome">[2] Guest Home</a>
    | <a href="/Home/UserHome">[4] User Home</a>
    | <a href="/Home/UserPrivate">[5] User Private Page</a>
    | <a href="/Home/UserFriends">[6] User Friends</a>
    | <a href="/Home/UserGuestView">[7] User Guest View</a>
    | <a href="/Home/UserBuying">[8,9] User Buying</a>
    | <a href="/Home/PagePrivate">[10] Page Private</a>
    | <a href="/Home/PageGuestView">[11] Page Guest View</a>
    | <a href="/Home/UserShops">[12] User Shops</a>
    | <a href="/Home/SearchResultPeople">[13] Search Result People</a>
    | <a href="/Home/SearchResultPosts">[14] Search Result Posts</a>
    | <a href="/Home/SearchResultShops">[15] Search Result Shops</a>
    | <a href="/Home/SearchResultProducts">[16] Search Result Products</a>
    | <a href="/Home/GuestCategories">[17] Guest Categories</a>
    | <a href="/Home/ProductDetails">[18] Product Details</a>
    | <a href="/Home/Checkout">[20] Đặt hàng</a>
    | <a href="/Home/Success">[21] Kết thúc</a>
    | <a href="/Home/Chat">[22] Chat</a>

</div>